-- Creates the Creatorverse database table.

-- Name, URL, and description are required.
-- Image URLs are optional.

create table if not exists creators (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null,
  name        text not null,
  url         text not null,
  description text not null,
  imageurl    text
);

-- This prework does not use user accounts, so RLS is disabled.
alter table creators disable row level security;