-- Creatorverse table definition.
-- Per the WEB103 prework, name / url / description are required and
-- imageurl is OPTIONAL, so it is the one nullable content column.

create table if not exists creators (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null,
  name        text not null,
  url         text not null,
  description text not null,
  imageurl    text
);

alter table creators disable row level security;
