-- ============================================================
-- Creatorverse — ONE-PASTE SETUP
--
-- Paste this whole file into the Supabase SQL Editor and press Run.
-- It creates the creators table and adds the sample creators.
-- Safe to re-run: the table is only created if it does not exist.
-- ============================================================

-- Creates the Creatorverse database table.

-- Name, URL, and description are required.
-- Image URLs are optional.

create table if not exists creators (
  id          bigint generated by default as identity primary key,
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null,
  name        text not null,
  url         text not null,
  description text not null,
  imageurl    text
);

-- This prework does not use user accounts, so RLS is disabled.
alter table creators disable row level security;
-- ---------- sample data ----------
-- Only inserts when the table is empty, so re-running will not duplicate.
do $$
begin
if not exists (select 1 from creators) then
  -- Adds sample creators to the database.
  -- Run once in the Supabase SQL Editor.
  -- Uses the same fields created in the creators table.
  
  insert into creators (name, url, description, imageurl) values
    (
      'Fireship',
      'https://www.youtube.com/@Fireship',
      'High-speed, high-density software tutorials. Best known for the "100 Seconds of Code" series that explains a whole framework before your coffee cools.',
      'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?auto=format&fit=crop&w=800&q=80'
    ),
    (
      'Kurzgesagt – In a Nutshell',
      'https://www.youtube.com/@kurzgesagt',
      'Beautifully animated science explainers covering everything from black holes to the immune system, with research notes published for every video.',
      'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=80'
    ),
    (
      'Marques Brownlee',
      'https://www.youtube.com/@mkbhd',
      'Widely regarded as the sharpest consumer tech reviewer on the internet. Studio-grade production and refreshingly blunt verdicts on phones, EVs, and gadgets.',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80'
    ),
    (
      'Adam Savage’s Tested',
      'https://www.youtube.com/@tested',
      'One-day builds, prop replicas, and shop-tool deep dives from the former MythBusters host. A masterclass in making things with your hands.',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80'
    ),
    (
      'Ali Abdaal',
      'https://www.youtube.com/@aliabdaal',
      'A doctor-turned-creator covering evidence-based productivity, study techniques, and building a creative career without burning out.',
      'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80'
    );
end if;
end $$;
